sudo: required

services:
  - docker

install:
  - pip install --upgrade --user awscli

script:
  - ./bin/build.sh -p
  - ./bin/test.sh -p

after_success:
  - ./bin/docker-push.sh

notifications:
#  slack:
#    rooms:
#      - hackoregon2018:0hiZjZlexw6dfsIDpN4SsXls#disaster-resilience-backend